<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        // [ar name, en name, dial code, ISO2 code]
        $countries = [
            ['أفغانستان',           'Afghanistan',                   '93',   'af'],
            ['ألبانيا',             'Albania',                       '355',  'al'],
            ['الجزائر',             'Algeria',                       '213',  'dz'],
            ['أندورا',              'Andorra',                       '376',  'ad'],
            ['أنغولا',              'Angola',                        '244',  'ao'],
            ['الأرجنتين',           'Argentina',                     '54',   'ar'],
            ['أرمينيا',             'Armenia',                       '374',  'am'],
            ['أستراليا',            'Australia',                     '61',   'au'],
            ['النمسا',              'Austria',                       '43',   'at'],
            ['أذربيجان',            'Azerbaijan',                    '994',  'az'],
            ['البحرين',             'Bahrain',                       '973',  'bh'],
            ['بنغلاديش',            'Bangladesh',                    '880',  'bd'],
            ['بيلاروسيا',           'Belarus',                       '375',  'by'],
            ['بلجيكا',              'Belgium',                       '32',   'be'],
            ['بليز',                'Belize',                        '501',  'bz'],
            ['بنين',                'Benin',                         '229',  'bj'],
            ['بوتان',               'Bhutan',                        '975',  'bt'],
            ['بوليفيا',             'Bolivia',                       '591',  'bo'],
            ['البوسنة والهرسك',     'Bosnia and Herzegovina',        '387',  'ba'],
            ['بوتسوانا',            'Botswana',                      '267',  'bw'],
            ['البرازيل',            'Brazil',                        '55',   'br'],
            ['بروناي',              'Brunei',                        '673',  'bn'],
            ['بلغاريا',             'Bulgaria',                      '359',  'bg'],
            ['بوركينا فاسو',        'Burkina Faso',                  '226',  'bf'],
            ['بوروندي',             'Burundi',                       '257',  'bi'],
            ['كمبوديا',             'Cambodia',                      '855',  'kh'],
            ['الكاميرون',           'Cameroon',                      '237',  'cm'],
            ['كندا',                'Canada',                        '1',    'ca'],
            ['الرأس الأخضر',        'Cape Verde',                    '238',  'cv'],
            ['جمهورية أفريقيا الوسطى', 'Central African Republic',  '236',  'cf'],
            ['تشاد',                'Chad',                          '235',  'td'],
            ['تشيلي',               'Chile',                         '56',   'cl'],
            ['الصين',               'China',                         '86',   'cn'],
            ['كولومبيا',            'Colombia',                      '57',   'co'],
            ['جزر القمر',           'Comoros',                       '269',  'km'],
            ['الكونغو',             'Congo',                         '242',  'cg'],
            ['جمهورية الكونغو الديمقراطية', 'DR Congo',             '243',  'cd'],
            ['كوستاريكا',           'Costa Rica',                    '506',  'cr'],
            ['كوت ديفوار',          "Côte d'Ivoire",                 '225',  'ci'],
            ['كرواتيا',             'Croatia',                       '385',  'hr'],
            ['كوبا',                'Cuba',                          '53',   'cu'],
            ['قبرص',                'Cyprus',                        '357',  'cy'],
            ['التشيك',              'Czech Republic',                '420',  'cz'],
            ['الدنمارك',            'Denmark',                       '45',   'dk'],
            ['جيبوتي',              'Djibouti',                      '253',  'dj'],
            ['جمهورية الدومينيكان', 'Dominican Republic',            '1',    'do'],
            ['الإكوادور',           'Ecuador',                       '593',  'ec'],
            ['مصر',                 'Egypt',                         '20',   'eg'],
            ['السلفادور',           'El Salvador',                   '503',  'sv'],
            ['غينيا الاستوائية',    'Equatorial Guinea',             '240',  'gq'],
            ['إريتريا',             'Eritrea',                       '291',  'er'],
            ['إستونيا',             'Estonia',                       '372',  'ee'],
            ['إثيوبيا',             'Ethiopia',                      '251',  'et'],
            ['فيجي',                'Fiji',                          '679',  'fj'],
            ['فنلندا',              'Finland',                       '358',  'fi'],
            ['فرنسا',               'France',                        '33',   'fr'],
            ['الغابون',             'Gabon',                         '241',  'ga'],
            ['غامبيا',              'Gambia',                        '220',  'gm'],
            ['جورجيا',              'Georgia',                       '995',  'ge'],
            ['ألمانيا',             'Germany',                       '49',   'de'],
            ['غانا',                'Ghana',                         '233',  'gh'],
            ['اليونان',             'Greece',                        '30',   'gr'],
            ['غواتيمالا',           'Guatemala',                     '502',  'gt'],
            ['غينيا',               'Guinea',                        '224',  'gn'],
            ['غينيا بيساو',         'Guinea-Bissau',                 '245',  'gw'],
            ['غيانا',               'Guyana',                        '592',  'gy'],
            ['هايتي',               'Haiti',                         '509',  'ht'],
            ['هندوراس',             'Honduras',                      '504',  'hn'],
            ['المجر',               'Hungary',                       '36',   'hu'],
            ['آيسلندا',             'Iceland',                       '354',  'is'],
            ['الهند',               'India',                         '91',   'in'],
            ['إندونيسيا',           'Indonesia',                     '62',   'id'],
            ['إيران',               'Iran',                          '98',   'ir'],
            ['العراق',              'Iraq',                          '964',  'iq'],
            ['أيرلندا',             'Ireland',                       '353',  'ie'],
            ['إيطاليا',             'Italy',                         '39',   'it'],
            ['جامايكا',             'Jamaica',                       '1',    'jm'],
            ['اليابان',             'Japan',                         '81',   'jp'],
            ['الأردن',              'Jordan',                        '962',  'jo'],
            ['كازاخستان',           'Kazakhstan',                    '7',    'kz'],
            ['كينيا',               'Kenya',                         '254',  'ke'],
            ['الكويت',              'Kuwait',                        '965',  'kw'],
            ['قيرغيزستان',          'Kyrgyzstan',                    '996',  'kg'],
            ['لاوس',                'Laos',                          '856',  'la'],
            ['لاتفيا',              'Latvia',                        '371',  'lv'],
            ['لبنان',               'Lebanon',                       '961',  'lb'],
            ['ليسوتو',              'Lesotho',                       '266',  'ls'],
            ['ليبيريا',             'Liberia',                       '231',  'lr'],
            ['ليبيا',               'Libya',                         '218',  'ly'],
            ['ليختنشتاين',          'Liechtenstein',                 '423',  'li'],
            ['ليتوانيا',            'Lithuania',                     '370',  'lt'],
            ['لوكسمبورغ',           'Luxembourg',                    '352',  'lu'],
            ['مدغشقر',              'Madagascar',                    '261',  'mg'],
            ['مالاوي',              'Malawi',                        '265',  'mw'],
            ['ماليزيا',             'Malaysia',                      '60',   'my'],
            ['المالديف',            'Maldives',                      '960',  'mv'],
            ['مالي',                'Mali',                          '223',  'ml'],
            ['مالطا',               'Malta',                         '356',  'mt'],
            ['موريتانيا',           'Mauritania',                    '222',  'mr'],
            ['موريشيوس',            'Mauritius',                     '230',  'mu'],
            ['المكسيك',             'Mexico',                        '52',   'mx'],
            ['مولدوفا',             'Moldova',                       '373',  'md'],
            ['موناكو',              'Monaco',                        '377',  'mc'],
            ['منغوليا',             'Mongolia',                      '976',  'mn'],
            ['الجبل الأسود',        'Montenegro',                    '382',  'me'],
            ['المغرب',              'Morocco',                       '212',  'ma'],
            ['موزمبيق',             'Mozambique',                    '258',  'mz'],
            ['ميانمار',             'Myanmar',                       '95',   'mm'],
            ['ناميبيا',             'Namibia',                       '264',  'na'],
            ['نيبال',               'Nepal',                         '977',  'np'],
            ['هولندا',              'Netherlands',                   '31',   'nl'],
            ['نيوزيلندا',           'New Zealand',                   '64',   'nz'],
            ['نيكاراغوا',           'Nicaragua',                     '505',  'ni'],
            ['النيجر',              'Niger',                         '227',  'ne'],
            ['نيجيريا',             'Nigeria',                       '234',  'ng'],
            ['مقدونيا الشمالية',    'North Macedonia',               '389',  'mk'],
            ['النرويج',             'Norway',                        '47',   'no'],
            ['عُمان',               'Oman',                          '968',  'om'],
            ['باكستان',             'Pakistan',                      '92',   'pk'],
            ['فلسطين',              'Palestine',                     '970',  'ps'],
            ['بنما',                'Panama',                        '507',  'pa'],
            ['بابوا غينيا الجديدة', 'Papua New Guinea',              '675',  'pg'],
            ['باراغواي',            'Paraguay',                      '595',  'py'],
            ['بيرو',                'Peru',                          '51',   'pe'],
            ['الفلبين',             'Philippines',                   '63',   'ph'],
            ['بولندا',              'Poland',                        '48',   'pl'],
            ['البرتغال',            'Portugal',                      '351',  'pt'],
            ['قطر',                 'Qatar',                         '974',  'qa'],
            ['رومانيا',             'Romania',                       '40',   'ro'],
            ['روسيا',               'Russia',                        '7',    'ru'],
            ['رواندا',              'Rwanda',                        '250',  'rw'],
            ['المملكة العربية السعودية', 'Saudi Arabia',             '966',  'sa'],
            ['السنغال',             'Senegal',                       '221',  'sn'],
            ['صربيا',               'Serbia',                        '381',  'rs'],
            ['سيراليون',            'Sierra Leone',                  '232',  'sl'],
            ['سنغافورة',            'Singapore',                     '65',   'sg'],
            ['سلوفاكيا',            'Slovakia',                      '421',  'sk'],
            ['سلوفينيا',            'Slovenia',                      '386',  'si'],
            ['الصومال',             'Somalia',                       '252',  'so'],
            ['جنوب أفريقيا',        'South Africa',                  '27',   'za'],
            ['جنوب السودان',        'South Sudan',                   '211',  'ss'],
            ['إسبانيا',             'Spain',                         '34',   'es'],
            ['سريلانكا',            'Sri Lanka',                     '94',   'lk'],
            ['السودان',             'Sudan',                         '249',  'sd'],
            ['سورينام',             'Suriname',                      '597',  'sr'],
            ['السويد',              'Sweden',                        '46',   'se'],
            ['سويسرا',              'Switzerland',                   '41',   'ch'],
            ['سوريا',               'Syria',                         '963',  'sy'],
            ['تايوان',              'Taiwan',                        '886',  'tw'],
            ['طاجيكستان',           'Tajikistan',                    '992',  'tj'],
            ['تنزانيا',             'Tanzania',                      '255',  'tz'],
            ['تايلاند',             'Thailand',                      '66',   'th'],
            ['تيمور الشرقية',       'Timor-Leste',                   '670',  'tl'],
            ['توغو',                'Togo',                          '228',  'tg'],
            ['ترينيداد وتوباغو',    'Trinidad and Tobago',           '1',    'tt'],
            ['تونس',                'Tunisia',                       '216',  'tn'],
            ['تركيا',               'Turkey',                        '90',   'tr'],
            ['تركمانستان',          'Turkmenistan',                  '993',  'tm'],
            ['أوغندا',              'Uganda',                        '256',  'ug'],
            ['أوكرانيا',            'Ukraine',                       '380',  'ua'],
            ['الإمارات العربية المتحدة', 'United Arab Emirates',     '971',  'ae'],
            ['المملكة المتحدة',     'United Kingdom',                '44',   'gb'],
            ['الولايات المتحدة',    'United States',                 '1',    'us'],
            ['أوروغواي',            'Uruguay',                       '598',  'uy'],
            ['أوزبكستان',           'Uzbekistan',                    '998',  'uz'],
            ['فنزويلا',             'Venezuela',                     '58',   've'],
            ['فيتنام',              'Vietnam',                       '84',   'vn'],
            ['اليمن',               'Yemen',                         '967',  'ye'],
            ['زامبيا',              'Zambia',                        '260',  'zm'],
            ['زيمبابوي',            'Zimbabwe',                      '263',  'zw'],
            // Additional countries
            ['أنتيغوا وباربودا',    'Antigua and Barbuda',           '1268', 'ag'],
            ['جزر البهاما',         'Bahamas',                       '1242', 'bs'],
            ['بربادوس',             'Barbados',                      '1246', 'bb'],
            ['دومينيكا',            'Dominica',                      '1767', 'dm'],
            ['إسواتيني',            'Eswatini',                      '268',  'sz'],
            ['غرينادا',             'Grenada',                       '1473', 'gd'],
            ['كيريباتي',            'Kiribati',                      '686',  'ki'],
            ['جزر مارشال',          'Marshall Islands',              '692',  'mh'],
            ['ميكرونيزيا',          'Micronesia',                    '691',  'fm'],
            ['ناورو',               'Nauru',                         '674',  'nr'],
            ['بالاو',               'Palau',                         '680',  'pw'],
            ['سانت كيتس ونيفيس',   'Saint Kitts and Nevis',         '1869', 'kn'],
            ['سانت لوسيا',          'Saint Lucia',                   '1758', 'lc'],
            ['سانت فنسنت وجزر غرينادين', 'Saint Vincent and the Grenadines', '1784', 'vc'],
            ['ساموا',               'Samoa',                         '685',  'ws'],
            ['سان مارينو',          'San Marino',                    '378',  'sm'],
            ['ساو تومي وبرينسيبي',  'São Tomé and Príncipe',         '239',  'st'],
            ['سيشيل',               'Seychelles',                    '248',  'sc'],
            ['جزر سليمان',          'Solomon Islands',               '677',  'sb'],
            ['تونغا',               'Tonga',                         '676',  'to'],
            ['توفالو',              'Tuvalu',                        '688',  'tv'],
            ['فانواتو',             'Vanuatu',                       '678',  'vu'],
        ];

        foreach ($countries as [$ar, $en, $code, $iso]) {
            $existing = Country::where('flag', $iso)->first();
            if ($existing) {
                $existing->update(['code' => $code]);
                $existing->translateOrNew('ar')->name = $ar;
                $existing->translateOrNew('en')->name = $en;
                $existing->save();
            } else {
                Country::create([
                    'ar'   => ['name' => $ar],
                    'en'   => ['name' => $en],
                    'code' => $code,
                    'flag' => $iso,
                ]);
            }
        }

    }//end of run

}//end of seeder
