<?php

namespace Database\Seeders;

use App\Models\Governorate;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GovernoratesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('governorate_translations')->truncate();
        DB::table('governorates')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $governorates = [

            // ===== المملكة العربية السعودية (id=132) — IDs: 1-13 =====
            ['country_id' => 132, 'ar' => ['name' => 'منطقة الرياض'],           'en' => ['name' => 'Riyadh Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة مكة المكرمة'],      'en' => ['name' => 'Makkah Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة المدينة المنورة'],  'en' => ['name' => 'Madinah Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة القصيم'],           'en' => ['name' => 'Qassim Region']],
            ['country_id' => 132, 'ar' => ['name' => 'المنطقة الشرقية'],        'en' => ['name' => 'Eastern Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة عسير'],             'en' => ['name' => 'Asir Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة تبوك'],             'en' => ['name' => 'Tabuk Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة حائل'],             'en' => ['name' => 'Hail Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة الحدود الشمالية'], 'en' => ['name' => 'Northern Borders Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة جازان'],            'en' => ['name' => 'Jazan Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة نجران'],            'en' => ['name' => 'Najran Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة الباحة'],           'en' => ['name' => 'Baha Region']],
            ['country_id' => 132, 'ar' => ['name' => 'منطقة الجوف'],            'en' => ['name' => 'Jouf Region']],

            // ===== مصر (id=48) — IDs: 14-40 =====
            ['country_id' => 48, 'ar' => ['name' => 'القاهرة'],       'en' => ['name' => 'Cairo']],
            ['country_id' => 48, 'ar' => ['name' => 'الجيزة'],        'en' => ['name' => 'Giza']],
            ['country_id' => 48, 'ar' => ['name' => 'الإسكندرية'],    'en' => ['name' => 'Alexandria']],
            ['country_id' => 48, 'ar' => ['name' => 'القليوبية'],     'en' => ['name' => 'Qalyubia']],
            ['country_id' => 48, 'ar' => ['name' => 'الشرقية'],       'en' => ['name' => 'Sharqia']],
            ['country_id' => 48, 'ar' => ['name' => 'الدقهلية'],      'en' => ['name' => 'Dakahlia']],
            ['country_id' => 48, 'ar' => ['name' => 'البحيرة'],       'en' => ['name' => 'Beheira']],
            ['country_id' => 48, 'ar' => ['name' => 'الغربية'],       'en' => ['name' => 'Gharbia']],
            ['country_id' => 48, 'ar' => ['name' => 'المنوفية'],      'en' => ['name' => 'Monufia']],
            ['country_id' => 48, 'ar' => ['name' => 'كفر الشيخ'],     'en' => ['name' => 'Kafr el-Sheikh']],
            ['country_id' => 48, 'ar' => ['name' => 'دمياط'],         'en' => ['name' => 'Damietta']],
            ['country_id' => 48, 'ar' => ['name' => 'بورسعيد'],       'en' => ['name' => 'Port Said']],
            ['country_id' => 48, 'ar' => ['name' => 'الإسماعيلية'],   'en' => ['name' => 'Ismailia']],
            ['country_id' => 48, 'ar' => ['name' => 'السويس'],        'en' => ['name' => 'Suez']],
            ['country_id' => 48, 'ar' => ['name' => 'شمال سيناء'],    'en' => ['name' => 'North Sinai']],
            ['country_id' => 48, 'ar' => ['name' => 'جنوب سيناء'],    'en' => ['name' => 'South Sinai']],
            ['country_id' => 48, 'ar' => ['name' => 'الفيوم'],        'en' => ['name' => 'Fayoum']],
            ['country_id' => 48, 'ar' => ['name' => 'بني سويف'],      'en' => ['name' => 'Beni Suef']],
            ['country_id' => 48, 'ar' => ['name' => 'المنيا'],        'en' => ['name' => 'Minya']],
            ['country_id' => 48, 'ar' => ['name' => 'أسيوط'],         'en' => ['name' => 'Assiut']],
            ['country_id' => 48, 'ar' => ['name' => 'سوهاج'],         'en' => ['name' => 'Sohag']],
            ['country_id' => 48, 'ar' => ['name' => 'قنا'],           'en' => ['name' => 'Qena']],
            ['country_id' => 48, 'ar' => ['name' => 'الأقصر'],        'en' => ['name' => 'Luxor']],
            ['country_id' => 48, 'ar' => ['name' => 'أسوان'],         'en' => ['name' => 'Aswan']],
            ['country_id' => 48, 'ar' => ['name' => 'البحر الأحمر'],  'en' => ['name' => 'Red Sea']],
            ['country_id' => 48, 'ar' => ['name' => 'الوادي الجديد'], 'en' => ['name' => 'New Valley']],
            ['country_id' => 48, 'ar' => ['name' => 'مطروح'],         'en' => ['name' => 'Matruh']],

            // ===== الإمارات العربية المتحدة (id=161) — IDs: 41-47 =====
            ['country_id' => 161, 'ar' => ['name' => 'أبوظبي'],    'en' => ['name' => 'Abu Dhabi']],
            ['country_id' => 161, 'ar' => ['name' => 'دبي'],        'en' => ['name' => 'Dubai']],
            ['country_id' => 161, 'ar' => ['name' => 'الشارقة'],    'en' => ['name' => 'Sharjah']],
            ['country_id' => 161, 'ar' => ['name' => 'عجمان'],      'en' => ['name' => 'Ajman']],
            ['country_id' => 161, 'ar' => ['name' => 'أم القيوين'], 'en' => ['name' => 'Umm Al Quwain']],
            ['country_id' => 161, 'ar' => ['name' => 'الفجيرة'],    'en' => ['name' => 'Fujairah']],
            ['country_id' => 161, 'ar' => ['name' => 'رأس الخيمة'], 'en' => ['name' => 'Ras Al Khaimah']],

            // ===== الكويت (id=82) — IDs: 48-53 =====
            ['country_id' => 82, 'ar' => ['name' => 'محافظة العاصمة'],       'en' => ['name' => 'Capital Governorate']],
            ['country_id' => 82, 'ar' => ['name' => 'محافظة حولي'],          'en' => ['name' => 'Hawalli Governorate']],
            ['country_id' => 82, 'ar' => ['name' => 'محافظة الفروانية'],     'en' => ['name' => 'Farwaniya Governorate']],
            ['country_id' => 82, 'ar' => ['name' => 'محافظة مبارك الكبير'], 'en' => ['name' => 'Mubarak Al-Kabeer Governorate']],
            ['country_id' => 82, 'ar' => ['name' => 'محافظة الأحمدي'],      'en' => ['name' => 'Ahmadi Governorate']],
            ['country_id' => 82, 'ar' => ['name' => 'محافظة الجهراء'],      'en' => ['name' => 'Jahra Governorate']],

            // ===== البحرين (id=11) — IDs: 54-57 =====
            ['country_id' => 11, 'ar' => ['name' => 'محافظة العاصمة'],    'en' => ['name' => 'Capital Governorate']],
            ['country_id' => 11, 'ar' => ['name' => 'المحافظة الشمالية'], 'en' => ['name' => 'Northern Governorate']],
            ['country_id' => 11, 'ar' => ['name' => 'المحافظة الجنوبية'], 'en' => ['name' => 'Southern Governorate']],
            ['country_id' => 11, 'ar' => ['name' => 'المحافظة الوسطى'],   'en' => ['name' => 'Central Governorate']],

            // ===== قطر (id=128) — IDs: 58-65 =====
            ['country_id' => 128, 'ar' => ['name' => 'الدوحة'],           'en' => ['name' => 'Doha']],
            ['country_id' => 128, 'ar' => ['name' => 'الريان'],           'en' => ['name' => 'Al Rayyan']],
            ['country_id' => 128, 'ar' => ['name' => 'الشمال'],           'en' => ['name' => 'Al Shamal']],
            ['country_id' => 128, 'ar' => ['name' => 'الخور والذخيرة'],  'en' => ['name' => 'Al Khor & Al Dhakhira']],
            ['country_id' => 128, 'ar' => ['name' => 'الوكرة'],           'en' => ['name' => 'Al Wakrah']],
            ['country_id' => 128, 'ar' => ['name' => 'أم صلال'],          'en' => ['name' => 'Umm Salal']],
            ['country_id' => 128, 'ar' => ['name' => 'الضعاين'],          'en' => ['name' => 'Al Daayen']],
            ['country_id' => 128, 'ar' => ['name' => 'الشحانية'],         'en' => ['name' => 'Al Shahaniya']],

            // ===== عُمان (id=118) — IDs: 66-76 =====
            ['country_id' => 118, 'ar' => ['name' => 'محافظة مسقط'],          'en' => ['name' => 'Muscat Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة ظفار'],          'en' => ['name' => 'Dhofar Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة مسندم'],         'en' => ['name' => 'Musandam Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة البريمي'],       'en' => ['name' => 'Al Buraimi Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة الداخلية'],      'en' => ['name' => 'Ad Dakhiliyah Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة الوسطى'],        'en' => ['name' => 'Al Wusta Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة شمال الشرقية'],  'en' => ['name' => 'North Al Sharqiyah']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة جنوب الشرقية'],  'en' => ['name' => 'South Al Sharqiyah']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة الظاهرة'],       'en' => ['name' => 'Al Dhahirah Governorate']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة شمال الباطنة'],  'en' => ['name' => 'North Al Batinah']],
            ['country_id' => 118, 'ar' => ['name' => 'محافظة جنوب الباطنة'],  'en' => ['name' => 'South Al Batinah']],

            // ===== الأردن (id=79) — IDs: 77-88 =====
            ['country_id' => 79, 'ar' => ['name' => 'محافظة عمان'],    'en' => ['name' => 'Amman Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة الزرقاء'], 'en' => ['name' => 'Zarqa Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة إربد'],    'en' => ['name' => 'Irbid Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة البلقاء'], 'en' => ['name' => 'Balqa Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة الكرك'],   'en' => ['name' => 'Karak Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة المفرق'],  'en' => ['name' => 'Mafraq Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة جرش'],     'en' => ['name' => 'Jerash Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة عجلون'],   'en' => ['name' => 'Ajloun Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة معان'],    'en' => ['name' => 'Maan Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة الطفيلة'], 'en' => ['name' => 'Tafilah Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة العقبة'],  'en' => ['name' => 'Aqaba Governorate']],
            ['country_id' => 79, 'ar' => ['name' => 'محافظة مادبا'],   'en' => ['name' => 'Madaba Governorate']],

            // ===== لبنان (id=86) — IDs: 89-96 =====
            ['country_id' => 86, 'ar' => ['name' => 'محافظة بيروت'],         'en' => ['name' => 'Beirut Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة جبل لبنان'],     'en' => ['name' => 'Mount Lebanon Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة الشمال'],        'en' => ['name' => 'North Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة عكار'],          'en' => ['name' => 'Akkar Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة البقاع'],        'en' => ['name' => 'Bekaa Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة بعلبك الهرمل'], 'en' => ['name' => 'Baalbek-Hermel Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة الجنوب'],        'en' => ['name' => 'South Governorate']],
            ['country_id' => 86, 'ar' => ['name' => 'محافظة النبطية'],       'en' => ['name' => 'Nabatieh Governorate']],

            // ===== سوريا (id=148) — IDs: 97-110 =====
            ['country_id' => 148, 'ar' => ['name' => 'محافظة دمشق'],       'en' => ['name' => 'Damascus']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة ريف دمشق'],   'en' => ['name' => 'Rif Dimashq']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة حلب'],        'en' => ['name' => 'Aleppo']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة حمص'],        'en' => ['name' => 'Homs']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة حماة'],       'en' => ['name' => 'Hama']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة اللاذقية'],   'en' => ['name' => 'Latakia']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة طرطوس'],      'en' => ['name' => 'Tartus']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة إدلب'],       'en' => ['name' => 'Idlib']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة دير الزور'],  'en' => ['name' => 'Deir ez-Zor']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة الحسكة'],     'en' => ['name' => 'Al-Hasakah']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة الرقة'],      'en' => ['name' => 'Raqqa']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة السويداء'],    'en' => ['name' => 'As-Suwayda']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة درعا'],       'en' => ['name' => 'Daraa']],
            ['country_id' => 148, 'ar' => ['name' => 'محافظة القنيطرة'],   'en' => ['name' => 'Quneitra']],

            // ===== العراق (id=74) — IDs: 111-128 =====
            ['country_id' => 74, 'ar' => ['name' => 'محافظة بغداد'],       'en' => ['name' => 'Baghdad']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة البصرة'],      'en' => ['name' => 'Basra']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة نينوى'],       'en' => ['name' => 'Nineveh']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة أربيل'],       'en' => ['name' => 'Erbil']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة السليمانية'],  'en' => ['name' => 'Sulaymaniyah']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة الأنبار'],     'en' => ['name' => 'Anbar']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة بابل'],        'en' => ['name' => 'Babylon']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة كربلاء'],      'en' => ['name' => 'Karbala']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة النجف'],       'en' => ['name' => 'Najaf']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة المثنى'],      'en' => ['name' => 'Muthanna']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة القادسية'],    'en' => ['name' => 'Al-Qadisiyyah']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة ذي قار'],      'en' => ['name' => 'Dhi Qar']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة ميسان'],       'en' => ['name' => 'Maysan']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة واسط'],        'en' => ['name' => 'Wasit']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة ديالى'],       'en' => ['name' => 'Diyala']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة كركوك'],       'en' => ['name' => 'Kirkuk']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة صلاح الدين'],  'en' => ['name' => 'Saladin']],
            ['country_id' => 74, 'ar' => ['name' => 'محافظة دهوك'],        'en' => ['name' => 'Dohuk']],

            // ===== اليمن (id=168) — IDs: 129-150 =====
            ['country_id' => 168, 'ar' => ['name' => 'أمانة العاصمة'],    'en' => ["name" => "Sana'a City"]],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة صنعاء'],     'en' => ["name" => "Sana'a"]],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة عدن'],       'en' => ['name' => 'Aden']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة تعز'],       'en' => ["name" => "Ta'iz"]],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة حضرموت'],    'en' => ['name' => 'Hadhramaut']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة مأرب'],      'en' => ['name' => 'Marib']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة شبوة'],      'en' => ['name' => 'Shabwah']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة أبين'],      'en' => ['name' => 'Abyan']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة لحج'],       'en' => ['name' => 'Lahij']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة الضالع'],    'en' => ['name' => 'Ad Dali']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة إب'],        'en' => ['name' => 'Ibb']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة ذمار'],      'en' => ['name' => 'Dhamar']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة البيضاء'],   'en' => ['name' => 'Al Bayda']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة حجة'],       'en' => ['name' => 'Hajjah']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة الحديدة'],   'en' => ['name' => 'Hudaydah']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة المحويت'],   'en' => ['name' => 'Al Mahwit']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة ريمة'],      'en' => ['name' => 'Raymah']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة عمران'],     'en' => ['name' => 'Amran']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة الجوف'],     'en' => ['name' => 'Al Jawf']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة صعدة'],      'en' => ["name" => "Sa'dah"]],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة المهرة'],    'en' => ['name' => 'Al Mahrah']],
            ['country_id' => 168, 'ar' => ['name' => 'محافظة سقطرى'],     'en' => ['name' => 'Socotra']],

            // ===== ليبيا (id=89) — IDs: 151-160 =====
            ['country_id' => 89, 'ar' => ['name' => 'طرابلس'],          'en' => ['name' => 'Tripoli']],
            ['country_id' => 89, 'ar' => ['name' => 'بنغازي'],          'en' => ['name' => 'Benghazi']],
            ['country_id' => 89, 'ar' => ['name' => 'مصراتة'],          'en' => ['name' => 'Misrata']],
            ['country_id' => 89, 'ar' => ['name' => 'الزاوية'],         'en' => ['name' => 'Zawiya']],
            ['country_id' => 89, 'ar' => ['name' => 'سبها'],            'en' => ['name' => 'Sabha']],
            ['country_id' => 89, 'ar' => ['name' => 'درنة'],            'en' => ['name' => 'Derna']],
            ['country_id' => 89, 'ar' => ['name' => 'الجبل الأخضر'],    'en' => ['name' => 'Al Jabal Al Akhdar']],
            ['country_id' => 89, 'ar' => ['name' => 'طبرق'],            'en' => ['name' => 'Tobruk']],
            ['country_id' => 89, 'ar' => ['name' => 'غريان'],           'en' => ['name' => 'Gharyan']],
            ['country_id' => 89, 'ar' => ['name' => 'الجفرة'],          'en' => ['name' => 'Al Jufra']],

            // ===== تونس (id=156) — IDs: 161-183 =====
            ['country_id' => 156, 'ar' => ['name' => 'ولاية تونس'],        'en' => ['name' => 'Tunis']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية أريانة'],      'en' => ['name' => 'Ariana']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية بن عروس'],     'en' => ['name' => 'Ben Arous']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية منوبة'],       'en' => ['name' => 'Manouba']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية نابل'],        'en' => ['name' => 'Nabeul']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية زغوان'],       'en' => ['name' => 'Zaghouan']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية بنزرت'],       'en' => ['name' => 'Bizerte']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية باجة'],        'en' => ['name' => 'Beja']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية جندوبة'],      'en' => ['name' => 'Jendouba']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية الكاف'],       'en' => ['name' => 'Kef']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية سليانة'],      'en' => ['name' => 'Siliana']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية القيروان'],     'en' => ['name' => 'Kairouan']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية القصرين'],      'en' => ['name' => 'Kasserine']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية سيدي بوزيد'],  'en' => ['name' => 'Sidi Bouzid']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية سوسة'],        'en' => ['name' => 'Sousse']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية المنستير'],     'en' => ['name' => 'Monastir']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية المهدية'],      'en' => ['name' => 'Mahdia']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية صفاقس'],       'en' => ['name' => 'Sfax']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية قفصة'],        'en' => ['name' => 'Gafsa']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية توزر'],        'en' => ['name' => 'Tozeur']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية قبلي'],        'en' => ['name' => 'Kebili']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية مدنين'],       'en' => ['name' => 'Medenine']],
            ['country_id' => 156, 'ar' => ['name' => 'ولاية تطاوين'],      'en' => ['name' => 'Tataouine']],

            // ===== الجزائر (id=3) — IDs: 184-229 =====
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الجزائر'],    'en' => ['name' => 'Algiers']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية البليدة'],     'en' => ['name' => 'Blida']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية بومرداس'],     'en' => ['name' => 'Boumerdes']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تيبازة'],      'en' => ['name' => 'Tipaza']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تيزي وزو'],    'en' => ['name' => 'Tizi Ouzou']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية بجاية'],       'en' => ['name' => 'Bejaia']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية جيجل'],        'en' => ['name' => 'Jijel']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية سطيف'],        'en' => ['name' => 'Setif']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية ميلة'],        'en' => ['name' => 'Mila']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية قسنطينة'],     'en' => ['name' => 'Constantine']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية سكيكدة'],      'en' => ['name' => 'Skikda']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية عنابة'],       'en' => ['name' => 'Annaba']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية قالمة'],       'en' => ['name' => 'Guelma']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية سوق أهراس'],   'en' => ['name' => 'Souk Ahras']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الطارف'],      'en' => ['name' => 'El Tarf']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية باتنة'],       'en' => ['name' => 'Batna']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية أم البواقي'],  'en' => ['name' => 'Oum El Bouaghi']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية خنشلة'],       'en' => ['name' => 'Khenchela']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تبسة'],        'en' => ['name' => 'Tebessa']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية بسكرة'],       'en' => ['name' => 'Biskra']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية ورقلة'],       'en' => ['name' => 'Ouargla']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الوادي'],      'en' => ['name' => 'El Oued']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية المسيلة'],     'en' => ['name' => "M'Sila"]],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية المدية'],      'en' => ['name' => 'Medea']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تيارت'],       'en' => ['name' => 'Tiaret']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تيسمسيلت'],    'en' => ['name' => 'Tissemsilt']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية وهران'],       'en' => ['name' => 'Oran']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية معسكر'],       'en' => ['name' => 'Mascara']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تلمسان'],      'en' => ['name' => 'Tlemcen']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية سعيدة'],       'en' => ['name' => 'Saida']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية عين تموشنت'],  'en' => ['name' => 'Ain Temouchent']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية سيدي بلعباس'], 'en' => ['name' => 'Sidi Bel Abbes']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية غليزان'],      'en' => ['name' => 'Relizane']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية مستغانم'],     'en' => ['name' => 'Mostaganem']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الشلف'],       'en' => ['name' => 'Chlef']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية عين الدفلى'],  'en' => ['name' => 'Ain Defla']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية البويرة'],     'en' => ['name' => 'Bouira']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الجلفة'],      'en' => ['name' => 'Djelfa']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية الأغواط'],     'en' => ['name' => 'Laghouat']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية غرداية'],      'en' => ['name' => 'Ghardaia']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية النعامة'],     'en' => ['name' => 'Naama']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية البيض'],       'en' => ['name' => 'El Bayadh']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية أدرار'],       'en' => ['name' => 'Adrar']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تندوف'],       'en' => ['name' => 'Tindouf']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية تمنراست'],     'en' => ['name' => 'Tamanrasset']],
            ['country_id' => 3, 'ar' => ['name' => 'ولاية إليزي'],       'en' => ['name' => 'Illizi']],

            // ===== المغرب (id=106) — IDs: 230-241 =====
            ['country_id' => 106, 'ar' => ['name' => 'جهة الرباط سلا القنيطرة'],    'en' => ['name' => 'Rabat-Sale-Kenitra']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة الدار البيضاء سطات'],     'en' => ['name' => 'Casablanca-Settat']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة مراكش آسفي'],             'en' => ['name' => 'Marrakesh-Safi']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة فاس مكناس'],              'en' => ['name' => 'Fes-Meknes']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة طنجة تطوان الحسيمة'],     'en' => ['name' => 'Tangier-Tetouan-Al Hoceima']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة الشرق'],                  'en' => ['name' => 'Oriental Region']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة بني ملال خنيفرة'],        'en' => ['name' => 'Beni Mellal-Khenifra']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة سوس ماسة'],               'en' => ['name' => 'Souss-Massa']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة درعة تافيلالت'],          'en' => ['name' => 'Draa-Tafilalet']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة كلميم واد نون'],          'en' => ['name' => 'Guelmim-Oued Noun']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة العيون الساقية الحمراء'], 'en' => ['name' => 'Laayoune-Sakia El Hamra']],
            ['country_id' => 106, 'ar' => ['name' => 'جهة الداخلة وادي الذهب'],    'en' => ['name' => 'Dakhla-Oued Ed-Dahab']],

            // ===== فلسطين (id=120) — IDs: 242-257 =====
            ['country_id' => 120, 'ar' => ['name' => 'محافظة القدس'],             'en' => ['name' => 'Jerusalem']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة رام الله والبيرة'], 'en' => ['name' => 'Ramallah and Al-Bireh']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة الخليل'],            'en' => ['name' => 'Hebron']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة بيت لحم'],           'en' => ['name' => 'Bethlehem']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة نابلس'],             'en' => ['name' => 'Nablus']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة طولكرم'],            'en' => ['name' => 'Tulkarm']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة قلقيلية'],           'en' => ['name' => 'Qalqilya']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة جنين'],              'en' => ['name' => 'Jenin']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة طوباس'],             'en' => ['name' => 'Tubas']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة سلفيت'],             'en' => ['name' => 'Salfit']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة أريحا والأغوار'],    'en' => ['name' => 'Jericho and Al Aghwar']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة غزة'],               'en' => ['name' => 'Gaza']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة شمال غزة'],          'en' => ['name' => 'North Gaza']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة دير البلح'],         'en' => ['name' => 'Deir al-Balah']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة خان يونس'],          'en' => ['name' => 'Khan Yunis']],
            ['country_id' => 120, 'ar' => ['name' => 'محافظة رفح'],               'en' => ['name' => 'Rafah']],

            // ===== السودان (id=144) — IDs: 258-275 =====
            ['country_id' => 144, 'ar' => ['name' => 'ولاية الخرطوم'],      'en' => ['name' => 'Khartoum']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية الجزيرة'],      'en' => ['name' => 'Al Jazirah']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية النيل الأبيض'], 'en' => ['name' => 'White Nile']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية النيل الأزرق'], 'en' => ['name' => 'Blue Nile']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية سنار'],         'en' => ['name' => 'Sennar']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية القضارف'],      'en' => ['name' => 'Gedaref']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية كسلا'],         'en' => ['name' => 'Kassala']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية البحر الأحمر'], 'en' => ['name' => 'Red Sea']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية نهر النيل'],    'en' => ['name' => 'River Nile']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية الشمالية'],     'en' => ['name' => 'Northern State']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية شمال كردفان'],  'en' => ['name' => 'North Kordofan']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية جنوب كردفان'],  'en' => ['name' => 'South Kordofan']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية غرب كردفان'],   'en' => ['name' => 'West Kordofan']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية شمال دارفور'],  'en' => ['name' => 'North Darfur']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية جنوب دارفور'],  'en' => ['name' => 'South Darfur']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية وسط دارفور'],   'en' => ['name' => 'Central Darfur']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية شرق دارفور'],   'en' => ['name' => 'East Darfur']],
            ['country_id' => 144, 'ar' => ['name' => 'ولاية غرب دارفور'],   'en' => ['name' => 'West Darfur']],

            // ===== الصومال (id=139) — IDs: 276-293 =====
            ['country_id' => 139, 'ar' => ['name' => 'بنادر (مقديشو)'],       'en' => ['name' => 'Banaadir (Mogadishu)']],
            ['country_id' => 139, 'ar' => ['name' => 'هيران'],                'en' => ['name' => 'Hiiraan']],
            ['country_id' => 139, 'ar' => ['name' => 'جلجدود'],               'en' => ['name' => 'Galgaduud']],
            ['country_id' => 139, 'ar' => ['name' => 'مدغ'],                  'en' => ['name' => 'Mudug']],
            ['country_id' => 139, 'ar' => ['name' => 'نوجال'],                'en' => ['name' => 'Nugaal']],
            ['country_id' => 139, 'ar' => ['name' => 'بري (بونتلاند)'],       'en' => ['name' => 'Bari (Puntland)']],
            ['country_id' => 139, 'ar' => ['name' => 'شبيلاها دوود'],         'en' => ['name' => 'Shabeellaha Dhexe']],
            ['country_id' => 139, 'ar' => ['name' => 'شبيلاها هوس'],          'en' => ['name' => 'Shabeellaha Hoose']],
            ['country_id' => 139, 'ar' => ['name' => 'جوبادا هوس (جوبالاند)'],'en' => ['name' => 'Jubbada Hoose (Jubaland)']],
            ['country_id' => 139, 'ar' => ['name' => 'جوبادا دوود'],          'en' => ['name' => 'Jubbada Dhexe']],
            ['country_id' => 139, 'ar' => ['name' => 'باي'],                  'en' => ['name' => 'Bay']],
            ['country_id' => 139, 'ar' => ['name' => 'باكول'],                'en' => ['name' => 'Bakool']],
            ['country_id' => 139, 'ar' => ['name' => 'وقوي قلب (صوماليلاند)'],'en' => ['name' => 'Woqooyi Galbeed (Somaliland)']],
            ['country_id' => 139, 'ar' => ['name' => 'أوداجي'],              'en' => ['name' => 'Awdal']],
            ['country_id' => 139, 'ar' => ['name' => 'طوخار'],               'en' => ['name' => 'Togdheer']],
            ['country_id' => 139, 'ar' => ['name' => 'سنعاق'],               'en' => ['name' => 'Sanaag']],
            ['country_id' => 139, 'ar' => ['name' => 'سول'],                 'en' => ['name' => 'Sool']],
            ['country_id' => 139, 'ar' => ['name' => 'جوبا السفلى'],         'en' => ['name' => 'Lower Juba']],

            // ===== موريتانيا (id=99) — IDs: 294-308 =====
            ['country_id' => 99, 'ar' => ['name' => 'ولاية نواكشوط الغربية'],  'en' => ['name' => 'Nouakchott Ouest']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية نواكشوط الشمالية'], 'en' => ['name' => 'Nouakchott Nord']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية نواكشوط الجنوبية'], 'en' => ['name' => 'Nouakchott Sud']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية الحوض الشرقي'],     'en' => ['name' => 'Hodh Ech Chargui']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية الحوض الغربي'],     'en' => ['name' => 'Hodh El Gharbi']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية العصابة'],          'en' => ['name' => 'Assaba']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية برقنه'],            'en' => ['name' => 'Brakna']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية تكانت'],            'en' => ['name' => 'Tagant']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية لبراكنه'],          'en' => ['name' => 'Guidimaka']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية ترارزه'],           'en' => ['name' => 'Trarza']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية آدرار'],            'en' => ['name' => 'Adrar']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية داخلت نواذيبو'],    'en' => ['name' => 'Dakhlet Nouadhibou']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية تيرس زمور'],        'en' => ['name' => 'Tiris Zemmour']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية إينشيري'],          'en' => ['name' => 'Inchiri']],
            ['country_id' => 99, 'ar' => ['name' => 'ولاية الشمامه (غورغول)'], 'en' => ['name' => 'Gorgol']],

            // ===== جيبوتي (id=45) — IDs: 309-314 =====
            ['country_id' => 45, 'ar' => ['name' => 'مدينة جيبوتي'], 'en' => ['name' => 'Djibouti City']],
            ['country_id' => 45, 'ar' => ['name' => 'علي صبيح'],     'en' => ['name' => 'Ali Sabieh']],
            ['country_id' => 45, 'ar' => ['name' => 'أرتا'],         'en' => ['name' => 'Arta']],
            ['country_id' => 45, 'ar' => ['name' => 'ديخيل'],        'en' => ['name' => 'Dikhil']],
            ['country_id' => 45, 'ar' => ['name' => 'عبيبة'],        'en' => ['name' => 'Obock']],
            ['country_id' => 45, 'ar' => ['name' => 'تجورة'],        'en' => ['name' => 'Tadjourah']],

            // ===== جزر القمر (id=35) — IDs: 315-317 =====
            ['country_id' => 35, 'ar' => ['name' => 'جزيرة نجازيجا (القمر الكبرى)'], 'en' => ['name' => 'Ngazidja (Grande Comore)']],
            ['country_id' => 35, 'ar' => ['name' => 'جزيرة موالي (موهيلي)'],          'en' => ['name' => 'Mwali (Moheli)']],
            ['country_id' => 35, 'ar' => ['name' => 'جزيرة نزواني (أنجوان)'],         'en' => ['name' => 'Nzwani (Anjouan)']],

            // ===== تركيا (id=157) — IDs: 318-398 =====
            ['country_id' => 157, 'ar' => ['name' => 'أضنة'],              'en' => ['name' => 'Adana']],
            ['country_id' => 157, 'ar' => ['name' => 'أدييامان'],          'en' => ['name' => 'Adıyaman']],
            ['country_id' => 157, 'ar' => ['name' => 'أفيون قره حصار'],    'en' => ['name' => 'Afyonkarahisar']],
            ['country_id' => 157, 'ar' => ['name' => 'أغري'],              'en' => ['name' => 'Ağrı']],
            ['country_id' => 157, 'ar' => ['name' => 'أماسيا'],            'en' => ['name' => 'Amasya']],
            ['country_id' => 157, 'ar' => ['name' => 'أنقرة'],             'en' => ['name' => 'Ankara']],
            ['country_id' => 157, 'ar' => ['name' => 'أنطاليا'],           'en' => ['name' => 'Antalya']],
            ['country_id' => 157, 'ar' => ['name' => 'أرتفين'],            'en' => ['name' => 'Artvin']],
            ['country_id' => 157, 'ar' => ['name' => 'أيدين'],             'en' => ['name' => 'Aydın']],
            ['country_id' => 157, 'ar' => ['name' => 'بالكسير'],           'en' => ['name' => 'Balıkesir']],
            ['country_id' => 157, 'ar' => ['name' => 'بيلجيك'],            'en' => ['name' => 'Bilecik']],
            ['country_id' => 157, 'ar' => ['name' => 'بينغول'],            'en' => ['name' => 'Bingöl']],
            ['country_id' => 157, 'ar' => ['name' => 'بتليس'],             'en' => ['name' => 'Bitlis']],
            ['country_id' => 157, 'ar' => ['name' => 'بولو'],              'en' => ['name' => 'Bolu']],
            ['country_id' => 157, 'ar' => ['name' => 'بوردور'],            'en' => ['name' => 'Burdur']],
            ['country_id' => 157, 'ar' => ['name' => 'بورصة'],             'en' => ['name' => 'Bursa']],
            ['country_id' => 157, 'ar' => ['name' => 'جاناق قلعة'],        'en' => ['name' => 'Çanakkale']],
            ['country_id' => 157, 'ar' => ['name' => 'جانكيري'],           'en' => ['name' => 'Çankırı']],
            ['country_id' => 157, 'ar' => ['name' => 'جوروم'],             'en' => ['name' => 'Çorum']],
            ['country_id' => 157, 'ar' => ['name' => 'دنيزلي'],            'en' => ['name' => 'Denizli']],
            ['country_id' => 157, 'ar' => ['name' => 'ديار بكر'],          'en' => ['name' => 'Diyarbakır']],
            ['country_id' => 157, 'ar' => ['name' => 'إدرنة'],             'en' => ['name' => 'Edirne']],
            ['country_id' => 157, 'ar' => ['name' => 'الازيغ'],            'en' => ['name' => 'Elazığ']],
            ['country_id' => 157, 'ar' => ['name' => 'إرزينجان'],          'en' => ['name' => 'Erzincan']],
            ['country_id' => 157, 'ar' => ['name' => 'أرضروم'],            'en' => ['name' => 'Erzurum']],
            ['country_id' => 157, 'ar' => ['name' => 'إسكي شهير'],         'en' => ['name' => 'Eskişehir']],
            ['country_id' => 157, 'ar' => ['name' => 'غازي عنتاب'],        'en' => ['name' => 'Gaziantep']],
            ['country_id' => 157, 'ar' => ['name' => 'غيرسون'],            'en' => ['name' => 'Giresun']],
            ['country_id' => 157, 'ar' => ['name' => 'غوموش هانة'],        'en' => ['name' => 'Gümüşhane']],
            ['country_id' => 157, 'ar' => ['name' => 'هكاري'],             'en' => ['name' => 'Hakkari']],
            ['country_id' => 157, 'ar' => ['name' => 'هاتاي'],             'en' => ['name' => 'Hatay']],
            ['country_id' => 157, 'ar' => ['name' => 'إسبارطة'],           'en' => ['name' => 'Isparta']],
            ['country_id' => 157, 'ar' => ['name' => 'مرسين'],             'en' => ['name' => 'Mersin']],
            ['country_id' => 157, 'ar' => ['name' => 'إسطنبول'],           'en' => ['name' => 'İstanbul']],
            ['country_id' => 157, 'ar' => ['name' => 'إزمير'],             'en' => ['name' => 'İzmir']],
            ['country_id' => 157, 'ar' => ['name' => 'قرص'],               'en' => ['name' => 'Kars']],
            ['country_id' => 157, 'ar' => ['name' => 'قسطموني'],           'en' => ['name' => 'Kastamonu']],
            ['country_id' => 157, 'ar' => ['name' => 'قيصري'],             'en' => ['name' => 'Kayseri']],
            ['country_id' => 157, 'ar' => ['name' => 'قيرقلار إيلي'],      'en' => ['name' => 'Kırklareli']],
            ['country_id' => 157, 'ar' => ['name' => 'قيرشهير'],           'en' => ['name' => 'Kırşehir']],
            ['country_id' => 157, 'ar' => ['name' => 'قوجه إيلي'],         'en' => ['name' => 'Kocaeli']],
            ['country_id' => 157, 'ar' => ['name' => 'قونيه'],             'en' => ['name' => 'Konya']],
            ['country_id' => 157, 'ar' => ['name' => 'كوتاهية'],           'en' => ['name' => 'Kütahya']],
            ['country_id' => 157, 'ar' => ['name' => 'ملاطية'],            'en' => ['name' => 'Malatya']],
            ['country_id' => 157, 'ar' => ['name' => 'منيسا'],             'en' => ['name' => 'Manisa']],
            ['country_id' => 157, 'ar' => ['name' => 'قهرمان مرعش'],       'en' => ['name' => 'Kahramanmaraş']],
            ['country_id' => 157, 'ar' => ['name' => 'مردين'],             'en' => ['name' => 'Mardin']],
            ['country_id' => 157, 'ar' => ['name' => 'موغلة'],             'en' => ['name' => 'Muğla']],
            ['country_id' => 157, 'ar' => ['name' => 'موش'],               'en' => ['name' => 'Muş']],
            ['country_id' => 157, 'ar' => ['name' => 'نفشهير'],            'en' => ['name' => 'Nevşehir']],
            ['country_id' => 157, 'ar' => ['name' => 'نيغدة'],             'en' => ['name' => 'Niğde']],
            ['country_id' => 157, 'ar' => ['name' => 'أوردو'],             'en' => ['name' => 'Ordu']],
            ['country_id' => 157, 'ar' => ['name' => 'رزة'],               'en' => ['name' => 'Rize']],
            ['country_id' => 157, 'ar' => ['name' => 'سقاريا'],            'en' => ['name' => 'Sakarya']],
            ['country_id' => 157, 'ar' => ['name' => 'سامسون'],            'en' => ['name' => 'Samsun']],
            ['country_id' => 157, 'ar' => ['name' => 'سيرت'],              'en' => ['name' => 'Siirt']],
            ['country_id' => 157, 'ar' => ['name' => 'سينوب'],             'en' => ['name' => 'Sinop']],
            ['country_id' => 157, 'ar' => ['name' => 'سيواس'],             'en' => ['name' => 'Sivas']],
            ['country_id' => 157, 'ar' => ['name' => 'تكيرداغ'],           'en' => ['name' => 'Tekirdağ']],
            ['country_id' => 157, 'ar' => ['name' => 'طوقات'],             'en' => ['name' => 'Tokat']],
            ['country_id' => 157, 'ar' => ['name' => 'طرابزون'],           'en' => ['name' => 'Trabzon']],
            ['country_id' => 157, 'ar' => ['name' => 'تونجلي'],            'en' => ['name' => 'Tunceli']],
            ['country_id' => 157, 'ar' => ['name' => 'شانلي أورفا'],       'en' => ['name' => 'Şanlıurfa']],
            ['country_id' => 157, 'ar' => ['name' => 'أوشاق'],             'en' => ['name' => 'Uşak']],
            ['country_id' => 157, 'ar' => ['name' => 'وان'],               'en' => ['name' => 'Van']],
            ['country_id' => 157, 'ar' => ['name' => 'يوزغات'],            'en' => ['name' => 'Yozgat']],
            ['country_id' => 157, 'ar' => ['name' => 'زونغولداق'],         'en' => ['name' => 'Zonguldak']],
            ['country_id' => 157, 'ar' => ['name' => 'أقساراي'],           'en' => ['name' => 'Aksaray']],
            ['country_id' => 157, 'ar' => ['name' => 'بايبورت'],           'en' => ['name' => 'Bayburt']],
            ['country_id' => 157, 'ar' => ['name' => 'قارامان'],           'en' => ['name' => 'Karaman']],
            ['country_id' => 157, 'ar' => ['name' => 'قيريق قلعة'],        'en' => ['name' => 'Kırıkkale']],
            ['country_id' => 157, 'ar' => ['name' => 'باطمان'],            'en' => ['name' => 'Batman']],
            ['country_id' => 157, 'ar' => ['name' => 'شيرناق'],            'en' => ['name' => 'Şırnak']],
            ['country_id' => 157, 'ar' => ['name' => 'بارطين'],            'en' => ['name' => 'Bartın']],
            ['country_id' => 157, 'ar' => ['name' => 'أردهان'],            'en' => ['name' => 'Ardahan']],
            ['country_id' => 157, 'ar' => ['name' => 'إغدير'],             'en' => ['name' => 'Iğdır']],
            ['country_id' => 157, 'ar' => ['name' => 'يالوا'],             'en' => ['name' => 'Yalova']],
            ['country_id' => 157, 'ar' => ['name' => 'قرابوك'],            'en' => ['name' => 'Karabük']],
            ['country_id' => 157, 'ar' => ['name' => 'كيليس'],             'en' => ['name' => 'Kilis']],
            ['country_id' => 157, 'ar' => ['name' => 'عثمانية'],           'en' => ['name' => 'Osmaniye']],
            ['country_id' => 157, 'ar' => ['name' => 'دوزجة'],             'en' => ['name' => 'Düzce']],

        ];

        foreach ($governorates as $governorate) {
            Governorate::create($governorate);
        }
    }
}
